# Load Data

In [1]:
import pandas as pd
import numpy as np
import h5py

In [2]:
train_df = pd.read_csv('sample_train.csv')
test_df = pd.read_csv('sample_test.csv')

y_train = train_df['label']
y_test = test_df['label']

In [3]:
test_df.iloc[49]

label                   yulia
sequence       New folder (2)
path        data3_37980_0.png
Name: 49, dtype: object

In [4]:
hf = h5py.File('dataset.h5', 'r')

In [5]:
hf.keys()

<KeysViewHDF5 ['test', 'train']>

In [6]:
x_train = np.array(hf.get('train'))
x_test = np.array(hf.get('test'))

In [7]:
# x_train = np.concatenate([x_train, np.fliplr(x_train)])
# x_test = np.concatenate([x_test, np.fliplr(x_test)])

In [8]:
hf.close()

In [9]:
x_train[0]

array([-9.46990475e-02,  1.38954237e-01,  3.39604877e-02, -1.00928701e-01,
       -1.60528272e-01,  1.29940873e-02, -4.69262563e-02, -1.12855233e-01,
        1.23366311e-01, -7.69931227e-02,  1.85811684e-01,  2.72786245e-03,
       -2.17859387e-01,  3.83564271e-02, -5.63728102e-02,  5.92535511e-02,
       -1.84768066e-01, -9.96602178e-02, -8.28254819e-02, -4.69317660e-02,
        4.84925434e-02,  3.83870602e-02,  4.72353809e-02,  4.96574007e-02,
       -1.81168705e-01, -3.16519588e-01, -5.80420494e-02, -9.06093791e-02,
       -3.95942479e-05, -1.87233053e-02,  3.74258272e-02, -2.45035421e-02,
       -2.23142907e-01, -3.80598940e-03,  2.23853625e-03,  5.12725636e-02,
        2.89023481e-02, -3.00322697e-02,  1.47486806e-01, -1.49986371e-02,
       -2.00699747e-01,  1.80294402e-02,  5.45309409e-02,  2.40527213e-01,
        1.70173168e-01, -2.71004327e-02,  9.01268721e-02, -1.28049567e-01,
        9.36447755e-02, -1.74807683e-01,  1.07777372e-01,  1.02794513e-01,
        3.97927500e-02,  

# Klasifikasi

In [10]:
from lightgbm import LGBMClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [11]:
lb = LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [209]:
# y_train = np.repeat(y_train, 2)

In [210]:
# y_train = np.concatenate([y_train, y_train])
# y_test = np.concatenate([y_test, y_test])

In [26]:
clf = LGBMClassifier(random_state=42)
clf.fit(x_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=1000, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [28]:
clf.score(x_test, y_test)

0.6491228070175439

In [29]:
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(x_train_norm, y_train)
clf.score(x_test_norm, y_test)

NameError: name 'x_train_norm' is not defined

In [213]:
from sklearn.linear_model import SGDClassifier

In [243]:
clf = SGDClassifier(random_state=42, loss='modified_huber')
clf.fit(x_train_norm, y_train)
clf.score(x_test_norm, y_test)

0.7719298245614035

In [244]:
np.max(clf.predict_proba(x_test), axis=1)

array([0.19576046, 0.18199251, 0.28329389, 0.29855572, 0.25371775,
       0.315065  , 0.3585323 , 0.31810848, 0.7280874 , 0.28237165,
       0.1940706 , 0.19823356, 0.34459949, 0.27198078, 0.31496639,
       0.21554447, 0.58658848, 0.24707321, 0.24291271, 0.52582774,
       0.56350175, 0.30137654, 0.29987352, 0.2435931 , 0.30860133,
       0.29374385, 0.25385512, 0.26242579, 0.34296181, 0.34450171,
       0.33333333, 0.49070011, 0.39344129, 0.2733176 , 0.23481516,
       0.32946937, 0.35351574, 0.36464411, 0.30118749, 0.35624936,
       0.27191821, 0.35244017, 0.26173348, 0.3702075 , 0.24810009,
       0.21865936, 0.26342098, 0.43451392, 0.25017452, 0.28165777,
       0.25758817, 0.36384873, 0.30460898, 0.33047251, 0.30096442,
       0.47514142, 0.44087554])

In [245]:
from sklearn.svm import LinearSVC, SVC
from sklearn.preprocessing import Normalizer
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis

In [261]:
clf = LinearDiscriminantAnalysis(solver='lsqr')
clf.fit(x_train_norm, y_train)
clf.score(x_test_norm, y_test)

0.8245614035087719

In [262]:
np.max(clf.predict_proba(x_test_norm), axis=1)

array([0.99727574, 0.99877968, 0.99007699, 0.99999946, 0.88905436,
       0.99971846, 1.        , 1.        , 1.        , 1.        ,
       0.99999997, 1.        , 1.        , 0.99999958, 0.99999729,
       0.99996871, 0.99999727, 0.99997352, 0.66146331, 0.99984271,
       1.        , 1.        , 0.99990357, 1.        , 1.        ,
       0.99999998, 0.97607106, 0.99469681, 0.9996548 , 0.99999997,
       1.        , 1.        , 1.        , 0.99998768, 0.99754321,
       0.99996725, 1.        , 0.99956137, 0.99658734, 0.99320078,
       0.93935155, 1.        , 1.        , 1.        , 1.        ,
       0.9869657 , 0.90184743, 1.        , 1.        , 0.50703996,
       0.99999305, 0.99999904, 0.99996101, 0.48479612, 0.9986627 ,
       0.99997601, 0.99998533])

In [269]:
y_pred[49]

19

In [265]:
idx = np.where(y_pred != y_test)[0]

array([ 1,  3,  4, 26, 27, 28, 34, 39, 52, 53], dtype=int64)

In [266]:
np.max(clf.predict_proba(x_test_norm), axis=1)[idx]

array([0.99877968, 0.99999946, 0.88905436, 0.97607106, 0.99469681,
       0.9996548 , 0.99754321, 0.99320078, 0.99996101, 0.48479612])

In [267]:
np.max(clf.predict_proba(x_test_norm), axis=1)[np.where(y_pred == y_test)[0]]

array([0.99727574, 0.99007699, 0.99971846, 1.        , 1.        ,
       1.        , 1.        , 0.99999997, 1.        , 1.        ,
       0.99999958, 0.99999729, 0.99996871, 0.99999727, 0.99997352,
       0.66146331, 0.99984271, 1.        , 1.        , 0.99990357,
       1.        , 1.        , 0.99999998, 0.99999997, 1.        ,
       1.        , 1.        , 0.99998768, 0.99996725, 1.        ,
       0.99956137, 0.99658734, 0.93935155, 1.        , 1.        ,
       1.        , 1.        , 0.9869657 , 0.90184743, 1.        ,
       1.        , 0.50703996, 0.99999305, 0.99999904, 0.9986627 ,
       0.99997601, 0.99998533])

In [258]:
y_test[8]

2

In [255]:
y_pred = clf.predict(x_test_norm)
print(classification_report(y_pred=lb.inverse_transform(y_pred), y_true=lb.inverse_transform(y_test)))

              precision    recall  f1-score   support

        afif       1.00      0.50      0.67         4
        aldi       0.33      0.50      0.40         2
    bu nanik       1.00      1.00      1.00         8
       dandy       1.00      1.00      1.00         2
      dinial       1.00      1.00      1.00         1
       fadli       1.00      1.00      1.00         3
    fandykun       0.67      1.00      0.80         2
       felix       1.00      1.00      1.00         2
   ferdinand       1.00      1.00      1.00         2
          kc       0.00      0.00      0.00         3
        mala       1.00      1.00      1.00         3
       randi       0.67      1.00      0.80         2
      rangga       0.00      0.00      0.00         1
     safhira       1.00      1.00      1.00         3
      sherly       1.00      0.50      0.67         2
      syauqi       0.40      1.00      0.57         2
        timo       0.75      1.00      0.86         3
     yolanda       0.60    

c:\programdata\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [253]:
clf = LinearDiscriminantAnalysis(solver='lsqr')
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.8070175438596491

In [248]:
clf = QuadraticDiscriminantAnalysis()
clf.fit(x_train_norm, y_train)
clf.score(x_test_norm, y_test)

c:\programdata\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:693: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


0.05263157894736842

In [249]:
clf = QuadraticDiscriminantAnalysis()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

c:\programdata\anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:693: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


0.05263157894736842

In [229]:
clf = SVC(kernel='linear')
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.6842105263157895

In [238]:
clf = SVC(kernel='linear', random_state=42)
clf.fit(x_train_norm, y_train)
clf.score(x_test_norm, y_test)

0.5964912280701754

In [235]:
normalizer = Normalizer(norm='l2')
x_train_norm = normalizer.transform(x_train)
x_test_norm = normalizer.transform(x_test)

In [217]:
clf = LinearSVC(random_state=42)
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.8245614035087719

In [236]:
clf = LinearSVC(random_state=42)
clf.fit(x_train_norm, y_train)
clf.score(x_test_norm, y_test)

0.8070175438596491

In [218]:
from sklearn.calibration import CalibratedClassifierCV
cclf = CalibratedClassifierCV(base_estimator=LinearSVC(), cv=5)
cclf.fit(x_train, y_train)
cclf.score(x_test, y_test)

0.7894736842105263

In [228]:
np.max(cclf.predict_proba(x_test), axis=1)

array([0.49368995, 0.46110696, 0.44185788, 0.57829943, 0.42008104,
       0.55711782, 0.67720174, 0.66193548, 0.78812638, 0.79546206,
       0.56481974, 0.60001309, 0.7429521 , 0.71090808, 0.68449004,
       0.52683019, 0.56897346, 0.66197029, 0.25563668, 0.44948665,
       0.79919765, 0.75273842, 0.64132322, 0.5245697 , 0.79007162,
       0.71114629, 0.30988955, 0.41558806, 0.43490613, 0.50065843,
       0.62369345, 0.72338979, 0.63243107, 0.44674335, 0.29660491,
       0.57580139, 0.72219339, 0.704018  , 0.38233005, 0.28398571,
       0.33084378, 0.7404195 , 0.7657971 , 0.76055116, 0.77548407,
       0.64974852, 0.42923368, 0.52344182, 0.7327114 , 0.41649541,
       0.60705032, 0.56163644, 0.38407767, 0.49895698, 0.35542469,
       0.33358642, 0.64954184])

In [226]:
np.argmax(cclf.predict_proba(x_test)[0])

0

In [219]:
clf.score(x_train, y_train)

0.9798387096774194

In [220]:
y_pred = clf.predict(x_test)

In [221]:
print(classification_report(y_pred=lb.inverse_transform(y_pred), y_true=lb.inverse_transform(y_test)))

              precision    recall  f1-score   support

        afif       1.00      0.50      0.67         4
        aldi       0.67      1.00      0.80         2
    bu nanik       1.00      1.00      1.00         8
       dandy       1.00      1.00      1.00         2
      dinial       0.50      1.00      0.67         1
       fadli       0.50      0.67      0.57         3
    fandykun       0.67      1.00      0.80         2
       felix       1.00      1.00      1.00         2
   ferdinand       1.00      1.00      1.00         2
          kc       0.50      0.33      0.40         3
        mala       1.00      1.00      1.00         3
       randi       1.00      1.00      1.00         2
      rangga       0.00      0.00      0.00         1
     safhira       1.00      1.00      1.00         3
      sherly       0.33      0.50      0.40         2
      syauqi       0.67      1.00      0.80         2
        timo       1.00      1.00      1.00         3
     yolanda       1.00    

c:\programdata\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [151]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.7192982456140351

# Jarak

In [125]:
def distance(new_encoding, known_encodings):
    return np.linalg.norm(known_encodings - new_encoding, axis=1)

def compare_faces(known_encodings, new_encoding, tolerance=0.6):
    """
    Compare a list of face encodings against a candidate encoding to see if they match.
    :param known_face_encodings: A list of known face encodings
    :param face_encoding_to_check: A single face encoding to compare against the list
    :param tolerance: How much distance between faces to consider it a match. Lower is more strict. 0.6 is typical best performance.
    :return: A list of True/False values indicating which known_face_encodings match the face encoding to check
    """
    return list(distance(known_encodings, new_encoding) <= tolerance)

def recognize(known_encodings, new_encoding, tolerance=0.5):
    dist = distance(new_encoding, known_encodings)
    argmin = np.argmin(dist)
    if dist[argmin] <= tolerance:
        return argmin
    return None

In [124]:
lb.inverse_transform(y_train[compare_faces(x_train, x_test[0])])

array(['afif', 'afif', 'afif', 'afif', 'afif', 'afif', 'afif', 'afif',
       'fandykun', 'fandykun', 'mala', 'mala', 'rangga', 'syauqi'],
      dtype=object)

In [126]:
identities = [recognize(x_train, encoding) for encoding in x_test]

In [130]:
identities = [y_train[idx] if idx is not None else None for idx in identities]

In [136]:
classification_report(y_pred=lb.inverse_transform(identities), y_true=lb.inverse_transform(y_test))

TypeError: '>' not supported between instances of 'int' and 'NoneType'

In [135]:
for y_pred, y_true in zip(identities, y_test):
    name_pred = lb.inverse_transform([y_pred])[0] if y_pred else None
    name_true = lb.inverse_transform([y_true])[0]
    print(name_pred, name_true)

fandykun afif
None afif
None afif
fandykun afif
None aldi
aldi aldi
bu nanik bu nanik
bu nanik bu nanik
bu nanik bu nanik
bu nanik bu nanik
bu nanik bu nanik
bu nanik bu nanik
bu nanik bu nanik
bu nanik bu nanik
dandy dandy
felix dandy
dinial dinial
fadli fadli
sherly fadli
fadli fadli
aldi fandykun
fandykun fandykun
felix felix
felix felix
ferdinand ferdinand
ferdinand ferdinand
kc kc
dandy kc
syauqi kc
mala mala
mala mala
mala mala
randi randi
syauqi randi
fandykun rangga
safhira safhira
safhira safhira
safhira safhira
sherly sherly
sherly sherly
yolanda syauqi
syauqi syauqi
timo timo
timo timo
timo timo
yolanda yolanda
fadli yolanda
dinial yolanda
yoshima yoshima
yulia yulia
yulia yulia
fadli yulia
sherly yulia
sherly zakiya
yolanda zakiya
ferdinand zakiya
zakiya zakiya
